### ISSUE TITLE
does not detect apps loaded by js

### ISSUE THREAD

**Issue by siparker** [hunter-io/wappalyzer-api#4]
Similar to other implementations where requests is used instead of a headless browser this sometimes does not pick up apps that are loaded after initial page load by js includes or other methods.

Example https://www.amcharts.com/ with the chrome plugin for wappalyzer this shows jqueryUI but the docker api does not.

Could there be an enhancement whereby we could pass in a json file containing the complete source code of a page for analysis if it is available. or possibly use browserless as a source for the website source as it will load js files as expected?

**Comment by BastienL** [comment]
That is unfortunately a limitation we are aware of. As our support for this Docker image is really limited, we don't plan on adding it soon. But feel free to submit a PR that would enhance it.
