### ISSUE TITLE
is this the expected output format?

### ISSUE THREAD

**Issue by elvisisvan** [hunter-io/wappalyzer-api#8]
## one-liner json? ![extract-output](https://github.com/hunter-io/wappalyzer-api/assets/69122770/1a0a7e16-c7a1-431b-9ba4-62889ff9c4f1)

**Comment by BastienL** [comment]
@elvisisvan yes. Any JSON parsing library can then be used to pretty-print/format the output, but the response isn't expected to be human-readable.
